# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: constraints.xdc

# IP: ip/DATA_MEM/DATA_MEM.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DATA_MEM || ORIG_REF_NAME==DATA_MEM} -quiet] -quiet
