# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/86152/Desktop/CS/Lab/Lab4/test_1/test_1.srcs/sources_1/ip/INST_MEM/INST_MEM.xci
# IP: The module: 'INST_MEM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/86152/Desktop/CS/Lab/Lab4/test_1/test_1.gen/sources_1/ip/INST_MEM/INST_MEM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'INST_MEM'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/86152/Desktop/CS/Lab/Lab4/test_1/test_1.srcs/sources_1/ip/INST_MEM/INST_MEM.xci
# IP: The module: 'INST_MEM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/86152/Desktop/CS/Lab/Lab4/test_1/test_1.gen/sources_1/ip/INST_MEM/INST_MEM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'INST_MEM'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
